services:
  jekyll:
    build:
      context: .
      dockerfile: ./docker/jekyll/Dockerfile
    command: bundle exec jekyll serve --watch --host 0.0.0.0
    ports:
      - "4000:4000"
    volumes:
      - ./:/app
